export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INGREDIENT_FETCH_FAILED = 'INGREDIENT_FETCH_FAILED';

export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILED = 'PURCHASE_ORDER_FAILED';
export const PURCHASE_ORDER = 'PURCHASE_ORDER';
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'; // for handling the loading state